--- #YAML:1.0
name:               Music-Chord-Positions
version:            0.04
abstract:           generate various chord inversions and voicings
author:
    - Jeremy Mates <jmates@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                0
    List::MoreUtils:     0
    List::Util:          0
    Music::Chord::Note:  0
    Test::More:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
